### ISSUE TITLE
OxygenXML 24.1 schema-based completion capabilities for FHIR Release 4

### ISSUE THREAD

**Issue by tcalice** [raducoravu/hl7-framework#1]
I have installed the oXygen XML Editor framework for HL7® but am not able to access the schema-based completion capabilities when I attempt to author a sample FHIR message.

I am still getting the following oXygen XML error when I put "$schema": "fhir.schema.json" in my json file.

#/$schema: extraneous key [$schema] is not permitted

I appreciate any guidance that you could provide on this.

![screenshot-oxygenXML-Add-ons](https://user-images.githubusercontent.com/2622355/160944083-47ebfaf8-57ad-4c25-9a9b-3768ec80b830.png)
![screenshot-oxygenXML-ManageAddons](https://user-images.githubusercontent.com/2622355/160944086-228e1611-418f-445d-a3ec-66582d56385f.png)
![screenshot-oxygenXML-MISSING-TEMPLATE](https://user-images.githubusercontent.com/2622355/160944087-cb41e43b-d5e1-49a7-9827-445f528486
![screenshot-oxygenXML-validationerror](https://user-images.githubusercontent.com/2622355/160945060-3df9fd5c-8d9e-4173-81de-949dca1e1381.png)
62.png)

**Comment by raducoravu** [comment]
@tcalice I created this framework some years ago for validating XML documents with the HL7 XML Schema, the framework contains no support for validating JSON with JSON Schema.
Oxygen itself should have support to edit and validate JSON files with a JSON Schema file though:
https://www.oxygenxml.com/doc/versions/24.1/ug-editor/topics/json-validating-documents-against-schema.html

One way to validate your JSON with the schema without adding a reference to the schema inside it is to use our drop down "Validate" toolbar button, choose "Validate with..." and select the schema to validate it
